sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      - zlib1g-dev
      - python
      - python-virtualenv
      - python-pip
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra
      - librsvg2-bin
      - lua5.1
      - liblua5.1-0-dev
      - inotify-tools
      - python-dev
      - libxml2-dev
      - libxslt1-dev

language: csharp
mono:
  - latest

install:
  - ./tools/travis-ci/install-luarocks.sh
  - ./tools/travis-ci/install-bazel.sh
  - ./tools/travis-ci/install-ksp-libs.sh

script:
  - stty cols 120
  - ./tools/travis-ci/set-version.sh
  - bazel build //:krpc //doc:html //doc:compile-scripts //:csproj
  - xbuild KRPC.sln
  - bazel test //:test

after_script:
  - rm -rf lib/ksp

before_deploy:
  - ./tools/travis-ci/before-deploy.sh

deploy:
  provider: s3
  access_key_id: AKIAJY3TMSKHV7DOMMWA
  secret_access_key:
    secure: shO089eufeIp6PHqa9bVWww2iQIxGgNwhTDwPZkuKuup9ZKr9QuGAhO2VFzhYQHCy3FZuSsxcfB3PjX6wsw2HU0qW0g6VFKHSkEV2/1EOO+vf0EA+jT1E7NZquq/VQ43vqYEWKszbiwO/ZYcM+eNmf+8IBaizaM2Q3eGNk0mI/PjKPHu3EgYRUelXVhVTr7hxgoixQVATjCzHMZzo2iYXETnAZryFn3dgmPgzXmD13DZHsHzdITM86fOadk391s31Vfk79YkQXEyEUoYIRUYZmNBxZzRzXU9d6DSihvpTsNAhqTmTMVEabDup+vjy1kKZJ1J/KC1JaVjWhyV4632/tUeQelPhcgGS5/58qeZu9GWIz5IdP5r7RFsJyJvE4/BjSUAEy7iGi4V1csTa5xe5x0fQYGy5Q96q5za5328MYLgr8MtfWjuersbi1vEsisiUlrukFTj6s7pJio/Y9Qon6iz3yqAwfb0vNWTFLCvc/mveoX70lhTZgih/nvevVTZsnPfKnF1PFhx1yUYIKCV5JYQwVNhLP7/SJqKCh3Byi/ZE1wdvD/XQ8rPKlcBXYhfEZe2D7kJMxENGMI7FyyG6zY0PRKu9fk0rsFrosT4V0v20VYIvLJ1PWMVF86YaM29T13J1grNVF3OSS/y76gPNX1OGYP1THYYDW0At/a3DV0=
  bucket: krpc
  upload-dir: deploy
  skip_cleanup: true
  local_dir: deploy
  on:
    all_branches: true
